<?php //foreach ($this->getBlocks() as $block): ?>
<!--    <div class="siteblock">-->
<!--        <div class="block-title">--><?php //echo Mage::helper('siteblocks')->escapeHtml($block->getTitle()) ?><!--</div>-->
<!--        <div class="block-content">--><?php //echo Mage::helper('siteblocks')->escapeHtml($block->getContent()) ?><!--</div>-->
<!--    </div>-->
<?php //endforeach; ?>
certified
<img src="<?php echo $this->getKulik(); ?>" height="50" width="50">